version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - docker-jitsi-meet_meet.jitsi

networks:
  docker-jitsi-meet_meet.jitsi:
   external: true
