version: '3'

services:
  nginx:
    image: jitsi-nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-jitsi-meet_meet.jitsi

networks:
  docker-jitsi-meet_meet.jitsi:
    external: true
